name: Build Fedora ISO

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
      options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          dnf install -y lorax wget

      - name: Run ISO build script
        env:
          OS_VERSION_NUMBER: 44
          BUILD_DIR: ${{ github.workspace }}
        run: |
          chmod +x ./scripts/build_iso.sh
          ./scripts/build_iso.sh $OS_VERSION_NUMBER "$BUILD_DIR"

      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fedora-fantasy-hwqual.iso
          path: |
            *.iso
            **/*.iso
          if-no-files-found: error
